@Services.Azoai_HostAddress = https://localhost:7033

GET {{Services.Azoai_HostAddress}}
Accept: application/json

###

GET {{Services.Azoai_HostAddress}}/api
Accept: application/json

###

GET {{Services.Azoai_HostAddress}}/liveness
Accept: application/json

###

GET {{Services.Azoai_HostAddress}}/api/getcompletion?userInput=What%20is%20an%20apple?
Accept: application/json

